### ISSUE TITLE
Add FireHydrant connector and converters

### ISSUE THREAD

**Issue by sasher** [faros-ai/airbyte-connectors#323]

**Comment by sasher** [comment]
Similar to Zendesk

**Comment by willmarks** [comment]
Hey @huongtn,
I looked quickly at what was available in FireHydrants APIs just to see what we would be interested in pulling. FireHydrant looks very similar to other incident management services (IMS) (e.g. PagerDuty, Datadog, VictorOps). We will want to pull the same information. This includes incidents, the applications that those incidents affect (using a service -> application mapping that is provided via the converter config), and the users within the system. Definitely use the existing converts as a reference as you do the work! Please reach out if you have any questions. Thanks!

**Comment by huongtn** [comment]
@willmarks thanks for your advice, I don't have any question for now.

**Comment by willmarks** [comment]
I think we could still use incremental mode but because there is not a way to order by updated_at, you will need to consider every ticket each time the connector is run. However, as you iterate across the incidents, you would only want to return those that are newer than the previously stored state. See the Datadog connector for a similar approach.
