### ISSUE TITLE
Azure ad connector is failing after pulling 100 users from ad we have around 3000 users

### ISSUE THREAD

**Issue by tovbinm** [faros-ai/airbyte-connectors#365]
Probably a bug in pagination?

**Comment by prakashcc** [comment]
Hi Team,

I was trying the azure ad connector and I select MongoDB as the destination. A few things I noticed are 

when I selected the 24hour replication frequency it started throwing the error after pulling 100 users and then I changed the frequency from 24 hours to 5 min, then it started pulling 100 users in each 5 min. I am not sure is it a bug or by design, it is like that but as a user, I expect the first sync should be completed without the frequency and then replication should work as expected.

**Comment by tovbinm** [comment]
Fixed in https://github.com/faros-ai/airbyte-connectors/pull/370
